config/routes.rb
Work6470::Application.routes.draw do

  root 'users#new'

  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :workouts, only: [:create, :destroy, :index]
  resources :workout_records, only: [:create, :destroy, :index]
  resources :goals, only: [:create, :destroy, :index]

  match '/signup', to: 'users#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/dashboard', to: 'workouts#index', via: 'get'
  match '/progress', to: 'workout_records#index', via: 'get'
  match '/achievements', to: 'achievements#index', via: 'get'
  match '/settings', to: 'users#show', via: 'get'

end

app/models/workout.rb
class Workout < ActiveRecord::Base
    belongs_to :user
    has_many :workout_records, dependent: :destroy
    has_many :goals

    include WorkoutsHelper

    # Returns sum of specified field values across
    # all workout records within the indicated time range
    # that are associated with the current workout instance.
    def sum_field_by_time_range(field, time_f)
        self.workout_records.select{ |r| time_f.call(r) }.map{ |r| r.send(field).to_f }.sum
    end

    def sum_field_by_custom_time_range(field, time_f, start_time, end_time)
        self.workout_records.select{ |r| time_f.call(start_time, end_time, r) }.map{ |r| r.send(field).to_f }.sum
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  def index
    @workout = Workout.new
    @workout_record = WorkoutRecord.new
  end

  def show
  end

  def create
    @workout = Workout.new(workout_params)
    @workout.user_id = current_user.id

    if @workout.save
      current_user.update({:current_workout_id => @workout.id})
      redirect_to :back, notice: 'New workout added!'
    else
      flash[:error] = "Workout failed to save."
      redirect_to :back
    end
  end

  def update
    if @workout.update(workout_params)
      redirect_to @workout, notice: 'Workout was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    current_user.workouts.delete(@workout)
    if current_user.workouts.empty?
      current_user.update({:current_workout_id => nil})
    else
      current_user.update({:current_workout_id => current_user.workouts[0].id})
    end
    redirect_to :back
  end

  private

    def set_workout
      @workout = Workout.find(params[:id])
    end

    def workout_params
      params.require(:workout).permit(:name, :notes)
    end

end

app/helpers/workouts_helper.rb
module WorkoutsHelper

    # Allows usage of date.beginning_of_x
    require 'active_support/core_ext/date/calculations.rb'

    # Allows usage of Array.sum
    require 'active_support/core_ext/enumerable.rb'

    # Returns hash of workout record totals sorted by workout and date range
    # Used in '/progress'
    def record_totals
        workout_hash = Hash.new
        current_user.workouts.each do |w|
            # Today, This Week, This Month, This Year, Total [x2 for time & distance]
            inner_array = [
                w.sum_field_by_time_range(:duration, method(:this_day)),
                w.sum_field_by_time_range(:duration, method(:this_week)),
                w.sum_field_by_time_range(:duration, method(:this_month)),
                w.sum_field_by_time_range(:duration, method(:this_year)),
                w.sum_field_by_time_range(:duration, method(:total)),
                w.sum_field_by_time_range(:distance, method(:this_day)),
                w.sum_field_by_time_range(:distance, method(:this_week)),
                w.sum_field_by_time_range(:distance, method(:this_month)),
                w.sum_field_by_time_range(:distance, method(:this_year)),
                w.sum_field_by_time_range(:distance, method(:total))
            ]
            workout_hash[w] = inner_array
        end
        return workout_hash
    end

    def record_overall_total
        result_array = nil
        current_user.workouts.each do |w|
            # Today, This Week, This Month, This Year, Total [x2 for time & distance]
            inner_array = [
                w.sum_field_by_time_range(:duration, method(:this_day)),
                w.sum_field_by_time_range(:duration, method(:this_week)),
                w.sum_field_by_time_range(:duration, method(:this_month)),
                w.sum_field_by_time_range(:duration, method(:this_year)),
                w.sum_field_by_time_range(:duration, method(:total)),
                w.sum_field_by_time_range(:distance, method(:this_day)),
                w.sum_field_by_time_range(:distance, method(:this_week)),
                w.sum_field_by_time_range(:distance, method(:this_month)),
                w.sum_field_by_time_range(:distance, method(:this_year)),
                w.sum_field_by_time_range(:distance, method(:total))
            ]
            if result_array == nil
                result_array = inner_array
            else
                i = 0
                10.times do
                    result_array[i] += inner_array[i]
                    i += 1
                end
            end
        end
        return result_array
    end

    # Time range functions used by workout.sum_field_by_time_range
    def this_day(record)
        record.date == Date.today
    end

    def this_week(record)
        (Date.today.beginning_of_week(:sunday)..Date.today) === record.date
    end

    def this_month(record)
        (Date.today.beginning_of_month..Date.today) === record.date
    end

    def this_year(record)
        (Date.today.beginning_of_year..Date.today) === record.date
    end

    def total(record)
        true
    end

    # Returns an array where the 0th element is the total duration for (number) days ago, and the last is the total duration for the present day
    def history_by_time_period(workout,number,metric,time_period)
        multiplier = 1
        if time_period == "week"
            multiplier = 7
        elsif time_period == "month"
            multiplier = 30
        elsif time_period == "year"
            multiplier = 365
        end

        starting_date = Date.today.prev_day(number * multiplier).next_day
        result_array = []
        number.times do
            next_date = starting_date.next_day(multiplier).prev_day
            result_sum = workout.sum_field_by_custom_time_range(metric, method(:check_range), starting_date, next_date)
            result_array << result_sum
            starting_date = starting_date.next_day(multiplier)
        end
        return result_array
    end

    def history_by_time_period_all(number,metric,time_period)
        result_array = nil
        current_user.workouts.each do |w|
            if result_array == nil
                result_array = history_by_time_period(w,number,metric,time_period)
            else
                i = 0
                activity_array = history_by_time_period(w,number,metric,time_period)
                number.times do
                    result_array[i] += activity_array[i]
                    i += 1
                end
            end
        end
        return result_array
    end

    def cumulative_history_by_time_period(workout,number,metric,time_period)
        multiplier = 1
        if time_period == "week"
            multiplier = 7
        elsif time_period == "month"
            multiplier = 30
        elsif time_period == "year"
            multiplier = 365
        end

        starting_date = Date.today.prev_day(number * multiplier).next_day
        result_array = []
        result_sum = 0
        number.times do
            next_date = starting_date.next_day(multiplier).prev_day
            result_sum += workout.sum_field_by_custom_time_range(metric, method(:check_range), starting_date, next_date)
            result_array << result_sum
            starting_date = starting_date.next_day(multiplier)
        end
        return result_array
    end

    def cumulative_history_by_time_period_all(number,metric,time_period)
        result_array = nil
        current_user.workouts.each do |w|
            if result_array == nil
                result_array = cumulative_history_by_time_period(w,number,metric,time_period)
            else
                i = 0
                activity_array = cumulative_history_by_time_period(w,number,metric,time_period)
                number.times do
                    result_array[i] += activity_array[i]
                    i += 1
                end
            end
        end
        return result_array
    end


    def check_range(start_date,end_date,record)
        ((start_date..end_date) === record.date)
    end

end

app/views/workouts/_delete.html.erb
<div id="delete_form">
  <div class="xbutton">[x]</div>
  <div class="delete_lower">
  <center>
    Are you sure you want to remove this activity? All records for it will be permanently deleted.
  </center>
  <%= button_to "Ok", workout, :method => :delete, :size => 15 %>
  <%= button_to "Cancel", "javascript:;", :class => "cancel_button" %>
</div>
</div>

app/views/workouts/_form.html.erb
<div id="add_form">
  <div class="xbutton">[x]</div>

  <%= form_for(@workout) do |f| %>
    <% if @workout.errors.any? %>
        <div id="error_explanation">
          <ul>
          <% @workout.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

    <center>
      <%= f.text_field :name, :placeholder => "Enter an activity to add...", :size => '40' %>
    </center>
    <br>
    <%= f.submit "Ok", data: { disable_with: 'Adding...' } %>
  <% end %>

<!--#   <%= button_to "Cancel", "javascript:;", :class => "cancel_button" %> -->
</div>

app/views/workouts/index.html.erb
<div class="dashboard_background">

  <%= render '/layouts/navbar' %>

  <div class="dashboard_container">

    <%= render '/layouts/dropdown' %>

    <% if current_workout != nil %>
      <center>
          <%= button_to "Record Workout", "javascript:;", :id => current_workout.id, :class => "record_button" %>
      </center>

      <table class="dashboard_table">
        <tbody>
          <tr class="chart_row">
            <td class="goal_half">
              <div id="goal_title">
                Goals for this Activity
              </div>
              <% if current_workout.goals[0] != nil %>
                <table class="dashboard_table">
                  <tbody>
                    <% current_workout.goals.each do |goal| %>
                      <tr>
                        <td class="dashboard_goal_statement"> <%= goal.number %> <%= goal.metric %> / <%= goal.time_range %>
                        </td>
                        <td class="dashboard_goal">
                          <div id="<%= get_current_progress(goal) %>" class="dashboard_goal_graph" style="height:75px;"></div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
            <% end %>
            </td>
            <td class="progress_half">
              <div id="dashboard_progress_graph" style="width:95%; height:400px;"></div>
              <script type="text/javascript">
                var dashboard_progress_data = <%= history_by_time_period(current_workout,7,:duration,"day") %> ;
                var dashboard_total_data = <%= history_by_time_period_all(7,:duration,"day") %> ;
              </script>
              <br>
              <div id="dashboard_cumulative_graph" style="width:95%; height:400px;"></div>
              <script type="text/javascript">
                var dashboard_cumulative_progress_data = <%= cumulative_history_by_time_period(current_workout,7,:duration,"day") %> ;
                var dashboard_cumulative_total_data = <%= cumulative_history_by_time_period_all(7,:duration,"day") %> ;
              </script>
            </td>
          </tr>
        </tbody>
      </table>

      <!-- Overlay to display workout record entry form -->
      <div class="workout_record" id="<%= current_workout.id %>" style="display:none;">
        <%= render :partial => 'workout_records/form', :locals => { :workout => current_workout } %>
      </div>

    <% end %>
  </div>
</div>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @workout.name %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @workout.distance %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @workout.duration %>
</p>

<p>
  <strong>Reps:</strong>
  <%= @workout.reps %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @workout.notes %>
</p>

<p>
  <strong>Type:</strong>
  <%= @workout.type %>
</p>

<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>